package apperror

// Error code registry: <DOM><NNN>, a domain mnemonic plus a per-domain sequence. NOTE: append-only — never renumber, never reuse a retired code; 900-999 is reserved per domain for internal failures.
const (
	CodeTenantMissing   = "GEN001"
	CodeUnauthenticated = "GEN002"
	CodeForbidden       = "GEN003"
	CodeValidation      = "GEN004"
	CodeNotFound        = "GEN005"
	CodeAlreadyExists   = "GEN006"
	CodeUnexpectedError = "GEN900"

	CodeTodoNotFound       = "TDO001"
	CodeTodoInvalidTitle   = "TDO002"
	CodeTodoAlreadyDeleted = "TDO003"

	CodeUserNotFound      = "USR001"
	CodeUserAlreadyExists = "USR002"
	CodeUserNotInvited    = "USR003"
	CodeUserInvalidEmail  = "USR004"
	CodeUserInvalidName   = "USR005"

	CodeOrgNotFound          = "ORG001"
	CodeOrgAlreadyExists     = "ORG002"
	CodeOrgInvalidSlug       = "ORG003"
	CodeOrgInvalidName       = "ORG004"
	CodeOrgMembershipExists  = "ORG005"
	CodeOrgMembershipMissing = "ORG006"
	CodeOrgCreationDisabled  = "ORG007"
	CodeOrgSystemProtected   = "ORG008"
	CodeOrgSelfRemoval       = "ORG009"
	CodeOrgOwnerRemoval      = "ORG010"
	CodeOrgManagerRequired   = "ORG011"

	CodeProjectNotFound        = "PRJ001"
	CodeProjectAlreadyExists   = "PRJ002"
	CodeProjectInvalidSlug     = "PRJ003"
	CodeProjectSystemProtected = "PRJ004"
	CodeProjectUnresolved      = "PRJ005"

	CodeInviteNotFound    = "INV001"
	CodeInviteExpired     = "INV002"
	CodeInviteAlreadyUsed = "INV003"
	CodeInviteInvalidRole = "INV004"
	CodeInviteDisabled    = "INV005"

	CodeSignupRequired = "SGN001"

	CodeAuthInvalidCredentials = "AUT001" //nolint:gosec // error code, not a credential
	CodeAuthOIDCUnavailable    = "AUT002"
	CodeAuthOIDCClaimMissing   = "AUT003"

	CodeTokenExpired = "TKN001"

	CodeOnboardingRequired    = "ONB001"
	CodeOnboardingAlreadyDone = "ONB002"

	CodeEncryptionUnavailable = "ENC001"
	CodeEncryptionOpenFailed  = "ENC002"

	CodePostNotFound         = "BLG001"
	CodePostAlreadyExists    = "BLG002"
	CodePostInvalidTitle     = "BLG003"
	CodePostInvalidSlug      = "BLG004"
	CodePostInvalidBody      = "BLG005"
	CodePostCategoryRequired = "BLG006"
	CodePostStaleVersion     = "BLG007"

	CodeCategoryNotFound      = "CAT001"
	CodeCategoryAlreadyExists = "CAT002"
	CodeCategoryInvalidName   = "CAT003"
	CodeCategoryInUse         = "CAT004"

	CodeTagNotFound      = "TAG001"
	CodeTagAlreadyExists = "TAG002"
	CodeTagInvalidName   = "TAG003"
	CodeTagInUse         = "TAG004"

	CodeLedgerInvalidTimezone = "LDG001"
	CodeLedgerInvalidStartDay = "LDG002"
	CodeLedgerUnknownCurrency = "LDG003"

	CodeWalletNotFound      = "WLT001"
	CodeWalletInvalidName   = "WLT002"
	CodeWalletAlreadyExists = "WLT003"
	CodeWalletInvalidKind   = "WLT004"
	CodeWalletInUse         = "WLT005"
	CodeWalletAmbiguousName = "WLT006"
	CodeWalletArchived      = "WLT007"

	CodeTxCategoryNotFound      = "CTG001"
	CodeTxCategoryInvalidName   = "CTG002"
	CodeTxCategoryAlreadyExists = "CTG003"
	CodeTxCategoryInvalidKind   = "CTG004"
	CodeTxCategoryInUse         = "CTG005"
	CodeTxCategoryAmbiguousName = "CTG006"

	CodeTransactionNotFound             = "TXN001"
	CodeTransactionInvalidAmount        = "TXN002"
	CodeTransactionCurrencyMismatch     = "TXN003"
	CodeTransactionInvalidKind          = "TXN004"
	CodeTransactionSameWallet           = "TXN005"
	CodeTransactionCategoryKindMismatch = "TXN006"
	CodeTransactionWalletArchived       = "TXN007"
	CodeTransactionPeriodLocked         = "TXN008"
	CodeTransactionPeriodNotAdjacent    = "TXN009"
	CodeTransactionInvalidNote          = "TXN010"
	CodeTransactionSystemRecorded       = "TXN011"
	CodeTransactionAuthorMissing        = "TXN012"

	CodePeriodNotFound        = "PRD001"
	CodePeriodInvalidName     = "PRD002"
	CodePeriodInvalidRange    = "PRD003"
	CodePeriodOverlap         = "PRD004"
	CodePeriodAlreadyClosed   = "PRD005"
	CodePeriodNotClosed       = "PRD006"
	CodePeriodNotLatestClosed = "PRD007"
	CodePeriodAuthorMissing   = "PRD008"

	CodeOpensheetLinkNotFound        = "OSL001"
	CodeOpensheetInvalidSetting      = "OSL002"
	CodeOpensheetAPIKeyRequired      = "OSL003"
	CodeOpensheetSheetUnreachable    = "OSL004"
	CodeOpensheetShapeMismatch       = "OSL005"
	CodeOpensheetNoIDColumn          = "OSL006"
	CodeOpensheetSheetNotWritable    = "OSL007"
	CodeOpensheetContractUnsatisfied = "OSL008"
	CodeOpensheetUnavailable         = "OSL009"
	CodeOpensheetNotVerified         = "OSL010"
	CodeOpensheetLinkDisabled        = "OSL011"
	CodeOpensheetSyncRefused         = "OSL012"
	CodeOpensheetScopeMismatch       = "OSL013"
	CodeOpensheetRowRefused          = "OSL014"
	CodeOpensheetKeyUnreadable       = "OSL015"
	CodeOpensheetPrivateEndpoint     = "OSL016"

	CodeMCPUnauthenticated = "MCP001"

	CodeAPIKeyUnknownScope       = "APK001"
	CodeAPIKeyRetiredScope       = "APK002"
	CodeAPIKeyScopeLevel         = "APK003"
	CodeAPIKeyEmptyGrant         = "APK004"
	CodeAPIKeyGrantConflict      = "APK005"
	CodeAPIKeyBoundToProject     = "APK006"
	CodeAPIKeyAlreadyAllProjects = "APK007"
	CodeAPIKeyRevoked            = "APK008"
	CodeAPIKeyProjectNotInOrg    = "APK009"
	CodeAPIKeyExpiryRequired     = "APK010"
	CodeAPIKeyExpiryInPast       = "APK011"
	CodeAPIKeyExpiryTooLong      = "APK012"

	CodeWebhookEndpointNotFound     = "WHK001"
	CodeWebhookInvalidURL           = "WHK002"
	CodeWebhookInvalidEventTypes    = "WHK003"
	CodeWebhookEndpointLimit        = "WHK004"
	CodeWebhookDeliveryNotRetryable = "WHK005"
	CodeWebhookDeliveryNotFound     = "WHK006"
	CodeWebhookEndpointInactive     = "WHK007"
	CodeWebhookSecretConflict       = "WHK008"
)
